// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcvhdjhwehwbqysllqjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjdmhkamh3ZWh3YnF5c2xscWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODQ0NDMsImV4cCI6MjA3NDg2MDQ0M30.qe8y2UCu66KVoJPkXsSd8HF2478jc_u8Sq4y_kO6kfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});